# Lesson 4: pandas party!

In [14]:
import pandas as pd
import numpy as np

Ok so last time we discussed how to apply functions onto dataframes in pandas. I briefly mentioned that a lot of stats operations can be thought of in terms of a map-reduce framework: we alternate between mapping one set of values onto another (e.g, convert degrees to farenheight, dollars to pesos, etc.) and grouping/aggregating values (e.g, finding the sum score of a group, averaging trial performance for each subject, etc.). For mapping, we can usually use the apply() function to transform some columns into a new column.

Grouping/reducing is going to rely on the groupby() function. So let's say we have our demographic dataset from the last lesson

In [2]:
demo_df=pd.read_csv('Demographic_Statistics_By_Zip_Code.csv')
demo_df.head() # head shows us the first five rows of the dataframe

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
0,10001,44,22,0.50,22,0.50,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
1,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
2,10003,1,1,1.00,0,0.00,0,0,1,100,...,1,100,0,0.00,1,1.00,0,0,1,100
3,10004,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0,0.00,0,0.00,0,0,0,0
4,10005,2,2,1.00,0,0.00,0,0,2,100,...,2,100,0,0.00,2,1.00,0,0,2,100

And suppose for each row I use apply to create a new column saying whether there's more males of more females

In [10]:
def more_female(row):
    if row['PERCENT FEMALE']>=.5:
        return True
    else:
        return False

demo_df.loc[:,'MORE FEMALE']=demo_df.apply(more_female,axis=1)
demo_df.head()

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL,MORE FEMALE
0,10001,44,22,0.50,22,0.50,0,0,44,100,...,100,20,0.45,24,0.55,0,0,44,100,True
1,10002,35,19,0.54,16,0.46,0,0,35,100,...,100,2,0.06,33,0.94,0,0,35,100,True
2,10003,1,1,1.00,0,0.00,0,0,1,100,...,100,0,0.00,1,1.00,0,0,1,100,True
3,10004,0,0,0.00,0,0.00,0,0,0,0,...,0,0,0.00,0,0.00,0,0,0,0,False
4,10005,2,2,1.00,0,0.00,0,0,2,100,...,100,0,0.00,2,1.00,0,0,2,100,True

I can then use groupby() to run statistics on districts that have more females and districts that have fewer. So I might find, for the districts that have more/less females, on average **HOW** many more/less females do they have?

In [12]:
demo_df.groupby('MORE FEMALE').mean()

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
MORE FEMALE,,,,,,,,,,,,,,,,,,,,,
False,11172.982353,8.800000,3.111765,0.058176,5.688235,0.171353,0.0,0.0,8.800000,22.941176,...,8.800000,22.941176,2.511765,0.060941,6.288235,0.168588,0.0,0.0,8.800000,22.941176
True,11009.181818,40.484848,28.803030,0.722576,11.681818,0.277424,0.0,0.0,40.484848,100.000000,...,40.484848,99.984848,14.893939,0.340758,25.590909,0.659242,0.0,0.0,40.484848,100.000000

And this returns a dataframe where the row indices are now the subset of trials where there were more or less females

If we just wanted the "PERCENT FEMALE" we could do something like

In [13]:
demo_df.groupby('MORE FEMALE').mean().loc[:,'PERCENT FEMALE']

MORE FEMALE
False    0.058176
True     0.722576
Name: PERCENT FEMALE, dtype: float64

What this says then is: 
* Districts where females are in the minority have ~5% females
* Districts where females are the majority have ~72% females

Note, the apply function works here too

In [16]:
demo_df.groupby('MORE FEMALE').apply(np.mean)

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL,MORE FEMALE
MORE FEMALE,,,,,,,,,,,,,,,,,,,,,
False,11172.982353,8.800000,3.111765,0.058176,5.688235,0.171353,0.0,0.0,8.800000,22.941176,...,22.941176,2.511765,0.060941,6.288235,0.168588,0.0,0.0,8.800000,22.941176,0.0
True,11009.181818,40.484848,28.803030,0.722576,11.681818,0.277424,0.0,0.0,40.484848,100.000000,...,99.984848,14.893939,0.340758,25.590909,0.659242,0.0,0.0,40.484848,100.000000,1.0

# Default groupby functions

As we've seen, groupby() has some default functions that allow you to get useful statistics. groupby() itself returns a grouped dataframe option

In [17]:
demo_df.groupby('MORE FEMALE')

And this has some useful default functions like mean(), sum(), size()

In [19]:
demo_df.groupby('MORE FEMALE').size() # how many entries are in each group

MORE FEMALE
False    170
True      66
dtype: int64

In [27]:
demo_df.groupby('MORE FEMALE').sum().loc[:,'PERCENT FEMALE']

MORE FEMALE
False     9.89
True     47.69
Name: PERCENT FEMALE, dtype: float64

# reset_index()

groupby() returns an object called a series where the indices of the rows are our groups. Sometimes we'll want to turn these back into dataframes. We can use the reset_index() function for this

In [32]:
demo_df.groupby('MORE FEMALE').sum().loc[:,'PERCENT FEMALE'].reset_index()

  MORE FEMALE  PERCENT FEMALE
0       False            9.89
1        True           47.69

This may look pretty similar, but note that where the row labels were previously [False, True], they're now 0,1 (the order of the rows) and **MORE FEMALE** True/False has been moved to its own column. Ok, honestly this isn't a big deal now but later on we're going to learn how to merge dataframes based on columns they have in common and being able to turn information into columns is going to be pretty important

## Problem

This is going to be a two-step problem--First apply, then map

1. There is a column called **PERCENT RECEIVES PUBLIC ASSISTANCE**. Create a new column, **MAJORITY_ASSIST** that contains True is more than 50% of residents receive public assistance and false otherwise

2. Find the number of districts that receive public assistance vs. those that don't. Hint: use the **size()** function on a grouped dataframe